name: ave

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install nasm
      run: |
        sudo apt-get install nasm
    - name: Install vpx
      env:
        VPX_TESTS: --disable-unit-tests --disable-examples
        VPX_INSTALL: --disable-install-docs
      run: |
        git clone --depth 1 https://github.com/webmproject/libvpx.git
        cd libvpx
        ./configure --enable-pic $VPX_TESTS $VPX_INSTALL --prefix=$HOME/vpx_dir
        make -j12
        make install
    - name: Install aom
      run: |
        git clone --depth 1 https://aomedia.googlesource.com/aom 
        cd aom
        mkdir -p build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/aom_dir \
              -DBUILD_SHARED_LIBS=1 \
              -DENABLE_TESTS=0 \
              -DENABLE_EXAMPLES=0 \
              ..
        make -j12
        make install
    - name: Install opus
      run: |
        git clone https://github.com/xiph/opus.git
        cd opus
        ./autogen.sh 
        ./configure --prefix=$HOME/opus_dir
        make -j12
        make install
    - name: Run tests
      run: |
        export PKG_CONFIG_PATH=$HOME/vpx_dir/lib/pkgconfig:$PKG_CONFIG_PATH
        export PKG_CONFIG_PATH=$HOME/aom_dir/lib/pkgconfig:$PKG_CONFIG_PATH
        export LD_LIBRARY_PATH=$HOME/aom_dir/lib:$LD_LIBRARY_PATH
        export PKG_CONFIG_PATH=$HOME/opus_dir/lib/pkgconfig:$PKG_CONFIG_PATH
        export LD_LIBRARY_PATH=$HOME/opus_dir/lib:$LD_LIBRARY_PATH
        cargo test --all-features --verbose
